### ISSUE TITLE
Container do not start

### ISSUE THREAD

**Issue by DerDoubleD** [RaspAP/raspap-docker#11]
Host is Raspberry Pi 3B

**command:** 
docker run --name raspap -it -d --privileged --network=host -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN jrcichra/raspap-docker

**log:**
systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture arm.

Welcome to Debian GNU/Linux 10 (buster)!

Set hostname to <raspberrypi>.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.

Exiting PID 1...

**Comment by DNAScanner** [comment]
Got the same Issue

**Comment by conrad-roux** [comment]
Apparently this is Docker related - see this: https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva/1054414#1054414

I would also look at this - https://github.com/moby/moby/issues/42275
It would be nice if it can be fixed

**Comment by billz** [comment]
> Hi, I'll look at this over the weekend. I have a new Pi 400 ready to test RaspAP in docker on.

Great! You're welcome to [expense this purchase](https://opencollective.com/raspap/expenses) for the project, if you like. We have budget for it.

> I've been playing around with the idea of an Ansible playbook that installs RaspAP based on the Manual Installation steps

Something like this? 😉 https://github.com/RaspAP/raspap-ansible

**Comment by jrcichra** [comment]
> Great! You're welcome to [expense this purchase](https://opencollective.com/raspap/expenses) for the project, if you like. We have budget for it.

Neat! I'll look more into it.

> Something like this? 😉 https://github.com/RaspAP/raspap-ansible

I should have done my homework before tinkering. This is great! I'll start here.

**Comment by andylinton** [comment]
Has there been any progress with this? I would like to run RaspAP in a Docker container but I can't get it to start, same error as above.

**Comment by Jarusz** [comment]
I'd love to hear about any kind of update, docker container would solve so much issues for me.

**Comment by kpma1985** [comment]
i created a dockerfile.. tested on nanopi and jetson nano

**Comment by cwong-archy** [comment]
any update? getting same error as well.

**Comment by DEPSTRCZ** [comment]
Yep, same error.

**Comment by NL-TCH** [comment]
fixed in #20 /close
