### ISSUE TITLE
Create a RPi-compatible Docker image for RaspAP

### ISSUE THREAD

**Issue by billz** [RaspAP/raspap-docker#18]
## Is your feature request related to a problem? 
RaspAP's existing Docker container fails to start on current Raspberry Pi hosts. See #11.

## Describe the solution you'd like
The Docker image needs to be refactored and brought up-to-date to make it functional with current ARMv7/8 architectures. 64- and 32-bit RPi OS bookworm and bullseye Lite distributions should be used as the reference host OS. Support for additional OS's including Debian and Ubuntu Server is desirable. Refer to this project's [compatible operating systems](https://docs.raspap.com/#compatible-operating-systems).

## Describe alternatives you've considered
Several different approaches have been proposed in #11. Start with this repo's existing implementation, build from one of these methods or go your own direction. See also #12.

## Additional context
Related Docker implementations for the RPi include projects such as [pihole/pihole](https://hub.docker.com/r/pihole/pihole) and [others](https://hub.docker.com/search?q=RPI&architecture=arm).

See also RaspAP's [manual installation steps](https://docs.raspap.com/manual/) and [Ansible playbook](https://github.com/RaspAP/raspap-ansible).

**Comment by ezhil56x** [comment]
@billz I would like to work on this. Can I get this assigned?
/attempt #18

**Comment by billz** [comment]
PS: no one will be assigned, I will review all PRs. Thanks!

**Comment by NL-TCH** [comment]
Thanks guys,
It was a blast working with you! communication went very smoothly!
If you need any help in the future with python, bash, docker or K8S hit me up :)

Gr. NL-TCH

**Comment by billz** [comment]
@NL-TCH likewise! appreciate your responsiveness and enjoyed our collaboration :)
