### ISSUE TITLE
Latest publish does not show wireguard, openvpn, and adblock options

### ISSUE THREAD

**Issue by bkmartin** [RaspAP/raspap-docker#36]
## Bug description
Using the latest image, I don't see the wireguard, adblock, and openvpn options... i switched to the previous image and it works fine.  

this one works
```
image: ghcr.io/raspap/raspap-docker@sha256:dc146f5d81300333c6640f13540a8ae738626d208ad1c2d0e9b559d6bdf35cd0
```

## Related issues
- [x ] I have searched this repository for existing issues and pull requests that look similar 

## Steps to Reproduce
use docker-compose and latest image published yesterday

## These common fixes didn't resolve my issue

- [x ] I have tried removing/destroying my container, and re-creating a new container
- [ x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x ] I have tried running the default `docker run` example(s) in the readme (removing any customizations I added)
- [ x] I have tried a newer or older version of RaspAP Docker (depending what version the issue started in for me)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by bkmartin** [comment]
FYI, I did a host os install using the raspap installer and saw the same behavior... so likely the regression here is in the raspap installer script

**Comment by billz** [comment]
@bkmartin you are entirely correct. thanks for raising this
