### ISSUE TITLE
Problems having access to internet

### ISSUE THREAD

**Issue by angel41671** [RaspAP/raspap-docker#39]
Good afternoon. 

First of all I'd like to thank you in advance for your support and apologies if I'm not posting the issue in the proper place, I am quite new to this.

I have installed RaspAP in a docker via docker compose but I am struggling to get internet connection. In the "Networking" section I got the following interfaces:
<img width="964" alt="Captura de pantalla 2024-05-04 a las 17 11 57" src="https://github.com/RaspAP/raspap-docker/assets/54057871/ed1b2d3e-f10d-4dd5-a987-04081defffd5">

I have tried everything that my limited knowledge has allowed me in order to get internet connection via "end0" (which seems to be my eth0).

I got a Raspberry Pi 4, Raspberry PI OS 64 bit and I followed the installation instructions on https://docs.raspap.com/docker/ (via docker compose) as well as added the provided iptables rules (changing "eth0" for "end0")
 
Is anyone able to give me a hand?
Thank you.

**Comment by billz** [comment]
Hello and welcome. RaspAP only enforces the use of `eth0` in bridged AP mode. If you're using this mode, you'll need to change the `end0` interface name. Otherwise, your best course of action is to generate a [debug log](https://docs.raspap.com/ap-basics/#debug-log).

**Comment by imaerials** [comment]
Happening the same to me, Clean Raspberry Pi Os Installation (Bookworm), Installed docker following Docker site instructions. Spin up the docker compose file with uncommented feature for ARM and the ETH0 is being renamed to ENXBXXXXXXX , where the XXX represent the MAC addres . No internet so far.

**Comment by billz** [comment]
@imaerials follow the above recommendation and report your results

**Comment by billz** [comment]
The issue here concerns your `end0` interface and this project's [firewall rules](https://github.com/RaspAP/raspap-docker/blob/master/firewall-rules.sh). You'll need to either 1) rename this interface to `eth0`, or 2) substitute the new name in these rules. You should then have connectivity.

**Comment by imaerials** [comment]
@billz I understand that the name must match with the rules, but why is the name of the interface changing after installing RaspAP ? Thanks for your reply. :D

**Comment by billz** [comment]
If you haven't updated your Linux kernel in awhile, the recent 6.6.2x release has adopted predictable network interface names. The kernel is doing this--not RaspAP. See [this explanation](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) for more info. You can disable this by using raspi-config. The official docs discuss this.

**Comment by imaerials** [comment]
Thanks for the information... But, I did a full clean up:
- Configured the interface name with "raspi-config"
- Removed Docker 
- checked the name is back to eth0
- cleaned every thing around docker, iptables,etc
- At this point if is ETH0
- Re-installed docker
- re build the image with EHT0 line in script FWRules
- eth0 is back to ENXBXXXXXXXX

**Comment by billz** [comment]
This isn't strictly related to this project, so you'll need to sort it out.

**Comment by imaerials** [comment]
After modifying the script and rebuilding the image got it to work, internet! Now im seeing that the "Network online" indicators are still red. just FYI. Thanks
