### ISSUE TITLE
WiFi AP and Client 

### ISSUE THREAD

**Issue by myreal84** [RaspAP/raspap-docker#5]
Hello there, 

i have an instance of raspap running on Rasbian, it works good so far. Now iam trying to create alomst the same via your Docker Container.

1. I have an additional WiFi USB Device (its working on the other instance)
2. wlan0 should be WiFi Client
3. wlan1 should be WiFi AP

I am not able to rescan for WiFi Networks in Raspap-Docker. 
Both devices are connected to my Homenetwork with differnt IPs.
When i start the AP on wlan1 it creates the AP and im able to connect but without Internet connection.

Is there something on Rasbian i need to change?

**Comment by 1ubuntuuser** [comment]
I have a similar issue. Has anyone been able to get client mode to work? AP works fine but can't scan for networks... 

Env: Armbian 21.02.2 Buster with Linux 5.10.16-sunxi

Great work on this btw! Good to see how far the project is coming.

**Comment by NL-TCH** [comment]
@billz have you done any testing related to this?
it is quite an old issue, but might be related to masquerading/NAT rules.

**Comment by billz** [comment]
@NL-TCH scanning uses `wpa_cli`, the WPA command line client, which generally works independently from NAT. This functionality [got an overhaul](https://github.com/RaspAP/raspap-webgui/pull/1469) in a recent release so it may be resolved now, but needs further testing. Thanks for highlighting this.

**Comment by billz** [comment]
I'm able to reproduce this.

```
wpa_cli -i wlan1 scan
Failed to connect to non-global ctrl_ifname: wlan1  error: No such file or directory
```

This is a fairly common error related to wpa_supplicant. In this case, the container was missing a `/etc/wpa_supplicant/wpa_supplicant.conf` file that specifies the `ctrl_interface`:

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
```

With this done, reinitialize wpa_supplicant:

```
wpa_supplicant -i wlan0 -D wext -c/etc/wpa_supplicant/wpa_supplicant.conf -B
```

Thereafter scanning works as expected (also in RaspAP UI):

```
wpa_cli -i wlan0 scan
OK
wpa_cli -i wlan0 scan_results
bssid / frequency / signal level / flags / ssid
50:0f:f5:8a:ff:ff	2427	-11	[WPA-PSK-CCMP][WPA2-PSK-CCMP][ESS]	Tropical148td
```

**Comment by NL-TCH** [comment]
this adding of the /etc/wpa_supplicant/wpa_supplicant.conf, we can add this via the dockerfile, is that something that is required for every usecase? and will it not interfere when having one WLAN interface?
