### ISSUE TITLE
Is this project active, I get an error out of the gate

### ISSUE THREAD

**Issue by snackwagon** [RaspAP/raspap-docker#6]
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by hippocritical** [comment]
this means your processor has the wrong architecture.

if you are running this on anything else than AMD64 you WILL get this error.

took me quite some time to get that aswell.

https://hub.docker.com/r/billzimmerman/raspap-docker/tags?page=1&ordering=last_updated
this states it is only available on AMD64 processors.


I find it QUITE AMUSING that something called "raspap" is NOT EVEN for the raspberry pi.
Painful how few effort is taken ...
